version: "3"
services:
  client:
    image: "dasiloy/docker-express-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "dasiloy/docker-express-api"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - PORT=$PORT
  worker:
    image: "dasiloy/docker-express-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "dasiloy/docker-express-nginx"
    mem_limit: 128m
    hostname: router
    ports:
      - "80:80"